# Reshaping and Transposing 

### `reshape` vs. `resize` 

In [1]:
import numpy as np

In [2]:
grades = np.array([[87, 96, 70], [100, 87, 90]])

In [3]:
grades

array([[ 87,  96,  70],
       [100,  87,  90]])

In [4]:
# does not modify original array. Gives back new array
# Still two dimentational array but with just one row
grades.reshape(1, 6)

array([[ 87,  96,  70, 100,  87,  90]])

In [5]:
grades

array([[ 87,  96,  70],
       [100,  87,  90]])

In [6]:
grades.resize(1, 6)

In [7]:
grades

array([[ 87,  96,  70, 100,  87,  90]])

### `flatten` vs. `ravel` 

#### flatten - performs a deep copy
#### ravel - performs a shallow copy or a view

In [8]:
grades = np.array([[87, 96, 70], [100, 87, 90]])

In [9]:
grades

array([[ 87,  96,  70],
       [100,  87,  90]])

In [10]:
flattened = grades.flatten()

In [12]:
# in this case it is a sigle dimentational array
flattened

array([ 87,  96,  70, 100,  87,  90])

In [13]:
grades

array([[ 87,  96,  70],
       [100,  87,  90]])

In [14]:
flattened[0] = 100

In [17]:
# flattened is a deep copy
# modifying elements in flattened did not change original
# array
flattened

array([100,  96,  70, 100,  87,  90])

In [18]:
grades

array([[ 87,  96,  70],
       [100,  87,  90]])

In [19]:
raveled = grades.ravel()

In [20]:
raveled

array([ 87,  96,  70, 100,  87,  90])

In [21]:
grades

array([[ 87,  96,  70],
       [100,  87,  90]])

In [22]:
raveled[0] = 100

In [26]:
# ravel is shallow copy
# so changing element in raveled modifies original
raveled

array([100,  96,  70, 100,  87,  90])

In [27]:
grades

array([[100,  96,  70],
       [100,  87,  90]])

### Transposing Rows and Columns

In [30]:
grades.T

array([[100, 100],
       [ 96,  87],
       [ 70,  90]])

In [31]:
grades

array([[100,  96,  70],
       [100,  87,  90]])

### Horizontal and Vertical Stacking

In [32]:
grades2 = np.array([[94, 77, 90], [100, 81, 82]])

In [33]:
# horizontally stack arrays
np.hstack((grades, grades2))

array([[100,  96,  70,  94,  77,  90],
       [100,  87,  90, 100,  81,  82]])

In [34]:
# vertically stack arrays
np.vstack((grades,grades2))

array([[100,  96,  70],
       [100,  87,  90],
       [ 94,  77,  90],
       [100,  81,  82]])

In [ ]:
# exercies

In [36]:
a = np.array([[1,2,3], [4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
b = np.hstack((a,a))
b

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [41]:
c = np.vstack((b,b))
c

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6],
       [1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])