## Indexing and Slicing 

### Indexing with Two-Dimensional `array`s

In [1]:
import numpy as np

In [2]:
grades = np.array([[87, 96, 70], [100, 87, 90],
                   [94, 77, 90], [100, 81, 82]])

In [3]:
grades

array([[ 87,  96,  70],
       [100,  87,  90],
       [ 94,  77,  90],
       [100,  81,  82]])

In [4]:
grades[0, 1]  # row 0, column 1

96

### Selecting a Subset of a Two-Dimensional `array`’s Rows

In [5]:
grades[1]

array([100,  87,  90])

In [6]:
grades[0:2]

array([[ 87,  96,  70],
       [100,  87,  90]])

In [7]:
grades[[1, 3]]

array([[100,  87,  90],
       [100,  81,  82]])

### Selecting a Subset of a Two-Dimensional `array`’s Columns

In [8]:
grades[:, 0]

array([ 87, 100,  94, 100])

In [9]:
grades[:, 1:3]

array([[96, 70],
       [87, 90],
       [77, 90],
       [81, 82]])

In [10]:
grades[:, [0, 2]]

array([[ 87,  70],
       [100,  90],
       [ 94,  90],
       [100,  82]])

In [16]:
numbers = np.arange(1,16).reshape(3,5)
numbers

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [17]:
numbers[1]

array([ 6,  7,  8,  9, 10])

In [18]:
numbers[[0,2]]

array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15]])

In [23]:
numbers[:,1:4]

array([[ 2,  3,  4],
       [ 7,  8,  9],
       [12, 13, 14]])