# Views: Shallow Copies

In [1]:
import numpy as np

In [2]:
numbers = np.arange(1, 6)

In [3]:
numbers

array([1, 2, 3, 4, 5])

In [4]:
numbers2 = numbers.view()

In [5]:
numbers2

array([1, 2, 3, 4, 5])

In [6]:
id(numbers)

4596162160

In [7]:
id(numbers2)

4596090512

In [8]:
numbers[1] *= 10

In [9]:
numbers2

array([ 1, 20,  3,  4,  5])

In [10]:
numbers

array([ 1, 20,  3,  4,  5])

In [11]:
numbers2[1] /= 10

In [12]:
numbers

array([1, 2, 3, 4, 5])

In [13]:
numbers2

array([1, 2, 3, 4, 5])

### Slice Views

In [14]:
numbers2 = numbers[0:3]

In [15]:
numbers2

array([1, 2, 3])

In [16]:
id(numbers)

4596162160

In [17]:
id(numbers2)

4595442288

In [18]:
# numbers2 is a view for only first 3 elements,
# in this case we  are trying to access 4th element.
numbers2[3]

IndexError: index 3 is out of bounds for axis 0 with size 3

In [19]:
numbers[1] *= 20

In [20]:
numbers

array([ 1, 40,  3,  4,  5])

In [21]:
numbers2

array([ 1, 40,  3])

# Deep Copy

In [28]:
numbers

array([ 1, 40,  0,  4,  5])

In [29]:
numbers3 = numbers.copy()
numbers3

array([ 1, 40,  0,  4,  5])

In [30]:
id(numbers), id(numbers3)

(4596162160, 4683033840)

In [31]:
numbers[1] /= 10

In [32]:
numbers

array([1, 4, 0, 4, 5])

In [33]:
# note that modifying numbers nupmy array did not 
# affect numbers3 array
numbers3

array([ 1, 40,  0,  4,  5])