## NumPy Calculation Methods

In [1]:
import numpy as np

In [4]:
grades = np.array([[10,80,90,70],[11,82,94,75],
          [18,88,98,78],[15,85,85,75]])

In [5]:
grades

array([[10, 80, 90, 70],
       [11, 82, 94, 75],
       [18, 88, 98, 78],
       [15, 85, 85, 75]])

In [6]:
grades.sum()

1054

In [7]:
grades.min()

10

In [8]:
grades.max()

98

In [9]:
grades.mean()

65.875

In [10]:
grades.std()

31.05413619793666

In [11]:
grades.var()

964.359375

### Calculations by Row or Column

In [12]:
# axis 0 is column wise operation
grades.mean(axis=0)

array([13.5 , 83.75, 91.75, 74.5 ])

In [13]:
# axis 1 is row wise operation
grades.mean(axis=1)

array([62.5, 65.5, 70.5, 65. ])

In [ ]:
# create array of 12 random grades
# in range of 60 through 100 
# then reshape into 3 X 4 array
# calculate average for each row, column and overall

In [18]:
grades = np.random.randint(60,101,12).reshape(3,4)

In [19]:
grades

array([[88, 88, 86, 60],
       [74, 75, 91, 81],
       [84, 90, 89, 62]])

In [20]:
grades.mean() # overall mean

80.66666666666667

In [21]:
grades.mean(axis=0) # column wise mean

array([82.        , 84.33333333, 88.66666667, 67.66666667])

In [22]:
grades.mean(axis=1) # row wise mean

array([80.5 , 80.25, 81.25])