## Creating `arrays` from sequences

In [1]:
import numpy as np

In [2]:
numbers = np.array([2, 3, 5, 7, 11])

In [3]:
type(numbers)

numpy.ndarray

In [4]:
numbers

array([ 2,  3,  5,  7, 11])

### Multidimensional Arguments

In [5]:
np.array([[1, 2, 3], [4, 5, 6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
# creating a numpy array from list comprehension

n1 = np.array([ n for n in range(2,21,2) ])
n1

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [21]:
# two dimentional array from list comprehension
num = np.array([[n for n in range(2,11,2)],
          [n for n in range(1,10) if (n % 2 != 0)]])
num

array([[ 2,  4,  6,  8, 10],
       [ 1,  3,  5,  7,  9]])

In [22]:
num.dtype

dtype('int64')

In [23]:
# array dimention
num.ndim

2

In [24]:
# array shapre
num.shape

(2, 5)

In [25]:
## numpy multi dim array - each element should be of 
# same sizeb
# in this case you get error
np.array([1,2,3],[4,5,6,7])

TypeError: Field elements must be 2- or 3-tuples, got '4'

In [27]:
# size = row * col = total elements
num.size

10

In [28]:
num.itemsize

8

In [29]:
for row in num:
    print(row)

[ 2  4  6  8 10]
[1 3 5 7 9]


In [30]:
# flatten out the row structure
for i in num.flat:
    print(i, end=' ')

2 4 6 8 10 1 3 5 7 9 

# numpy zeros, ones

In [31]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [33]:
np.ones((2,5)) # give tuple as an argument with row, columns

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [34]:
# if you want integer arrays instead of floats
np.ones((2,5), dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [36]:
np.full((3,5), 18) # instead of ones/zeros use other number

array([[18, 18, 18, 18, 18],
       [18, 18, 18, 18, 18],
       [18, 18, 18, 18, 18]])